volumes:
  local_postgres_data : {}
  local_postgres_data_backups : {}
  pgadmin: {}

services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_SERVICE=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=billing_db
      - POSTGRES_USER=billing_db_admin
      - POSTGRES_PASSWORD=billing_db_admin_password
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL : admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD : password
      PGADMIN_LISTEN_PORT : 80
    ports:
      - '15432:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
  django:
    build: ./projects
    command: >
      sh -c "python manage.py migrate && python manage.py create_default_users && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./projects:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DJANGO_SETTINGS_MODULE=app-root.settings
      - DATABASE_URL=postgres://billing_db_admin:billing_db_admin_password@postgres:5432/billing_db
      - POSTGRES_HOST=postgres
