# Generated by Django 5.1 on 2025-07-25 12:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manager', '0004_jobseeker'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Intitulé du poste')),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI (Contrat à Durée Indéterminée)'), ('CDD', 'CDD (Contrat à Durée Déterminée)'), ('FREELANCE', 'Freelance'), ('INTERNSHIP', 'Stage'), ('APPRENTICESHIP', 'Apprentissage'), ('PART_TIME', 'Temps partiel')], max_length=20, verbose_name='Type de contrat')),
                ('contract_duration', models.IntegerField(blank=True, help_text='Laissez vide pour CDI ou contrat sans durée fixe', null=True, verbose_name='Durée du contrat (en mois)')),
                ('experience_required', models.CharField(choices=[('NO_EXPERIENCE', 'Débutant (0 an)'), ('JUNIOR', 'Junior (< 2 ans)'), ('MID_LEVEL', 'Intermédiaire (2-4 ans)'), ('SENIOR', 'Senior (5-8 ans)'), ('EXPERT', 'Expert (> 10 ans)')], default='NO_EXPERIENCE', max_length=20, verbose_name='Expérience requise')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name="Référence de l'offre")),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire minimum')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire maximum')),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('location', models.CharField(blank=True, help_text="Laissez vide pour utiliser l'adresse de l'agence", max_length=255, null=True, verbose_name='Lieu de travail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Offre active')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='user_manager.agency', verbose_name='Agence')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-publication_date'],
            },
        ),
    ]
