# Generated by Django 5.1 on 2025-07-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agency',
        ),
    ]
